// <auto-generated />
using System;
using MVCProyectoPNT.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCProyectoPNT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241015032928_modificacionesenUsuario")]
    partial class modificacionesenUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCProyectoPNT.Entity.Archivo3D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RepositorioArchivosBorradosId")
                        .HasColumnType("int");

                    b.Property<int?>("RepositorioArchivosId")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tamano")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepositorioArchivosBorradosId");

                    b.HasIndex("RepositorioArchivosId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Archivos3D");
                });

            modelBuilder.Entity("MVCProyectoPNT.Entity.RepositorioArchivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("RepositorioArchivos");
                });

            modelBuilder.Entity("MVCProyectoPNT.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MVCProyectoPNT.Entity.Archivo3D", b =>
                {
                    b.HasOne("MVCProyectoPNT.Entity.RepositorioArchivos", "RepositorioArchivosBorrados")
                        .WithMany("ArchivosBorrados")
                        .HasForeignKey("RepositorioArchivosBorradosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MVCProyectoPNT.Entity.RepositorioArchivos", "RepositorioArchivos")
                        .WithMany("Archivos")
                        .HasForeignKey("RepositorioArchivosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MVCProyectoPNT.Entity.Usuario", "Usuario")
                        .WithMany("Archivos3D")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositorioArchivos");

                    b.Navigation("RepositorioArchivosBorrados");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MVCProyectoPNT.Entity.RepositorioArchivos", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("ArchivosBorrados");
                });

            modelBuilder.Entity("MVCProyectoPNT.Entity.Usuario", b =>
                {
                    b.Navigation("Archivos3D");
                });
#pragma warning restore 612, 618
        }
    }
}
